# Generated by Django 4.2.6 on 2023-10-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('event_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('event_street_address', models.CharField(max_length=100)),
                ('event_city', models.CharField(max_length=100)),
                ('event_state', models.CharField(max_length=100)),
                ('event_time_start', models.DateTimeField()),
                ('event_time_end', models.DateTimeField()),
                ('event_description', models.TextField()),
            ],
        ),
    ]
