# Generated by Django 4.2.6 on 2023-10-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo_event', '0002_remove_event_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(default='2000-01-01T00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.DateTimeField(default='2000-01-01T00:00'),
        ),
    ]
