# Generated by Django 4.2.6 on 2023-10-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo_event', '0003_event_event_end_time_event_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(default='pending'),
        ),
    ]
