# Generated by Django 4.2.6 on 2023-10-30 06:25

from django.db import migrations, models
import hoo_event.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo_event', '0004_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(default=hoo_event.models.EventStatus['PENDING']),
        ),
    ]
