# Generated by Django 4.2.6 on 2023-11-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo_event', '0005_alter_event_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_email',
            field=models.CharField(default='xwq5ja@virginia.edu', max_length=100),
            preserve_default=False,
        ),
    ]
