# Generated by Django 4.2.6 on 2023-11-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoo_event', '0006_event_event_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoo_event.event')),
            ],
        ),
    ]
