# Generated by Django 4.2.6 on 2023-11-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo_event', '0007_headcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
