# Generated by Django 4.2.6 on 2023-11-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo_event', '0009_event_event_full_capacity_alter_event_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default='Welcome to our event!'),
            preserve_default=False,
        ),
    ]
