# Generated by Django 4.2.6 on 2023-12-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoo_event", "0010_event_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_category",
            field=models.CharField(
                choices=[("1", "😊"), ("2", "🎉"), ("3", "🎈")], default=1
            ),
        ),
    ]
