# Generated by Django 4.2.6 on 2023-12-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoo_event', '0015_alter_event_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenyReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=100)),
                ('event_deny_reason', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoo_event.event')),
            ],
        ),
    ]
